name: Latex Compilation
on: [push]
jobs:
  Compile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Compilation
        uses: ./.github/actions/texlive-action
      - name: Upload Document
        uses: actions/upload-artifact@v2
        with:
          name: document
          path: article.pdf
          if-no-files-found: error
